import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['es', 'en', 'de', 'it', 'fr', 'pt', 'ar', 'ja'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? enText = '',
    String? deText = '',
    String? itText = '',
    String? frText = '',
    String? ptText = '',
    String? arText = '',
    String? jaText = '',
  }) =>
      [
        esText,
        enText,
        deText,
        itText,
        frText,
        ptText,
        arText,
        jaText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // auth_3_Create
  {
    '5fpmlflc': {
      'es': 'Crear Cuenta',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'en': 'Create Account',
      'fr': 'Créer un compte',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
    },
    'qux2kgj2': {
      'es': 'Empecemos rellenando el siguiente formulario.',
      'ar': 'لنبدأ بملء النموذج التالي.',
      'de': 'Beginnen wir mit dem Ausfüllen des folgenden Formulars.',
      'en': 'Let\'s get started by filling out the following form.',
      'fr': 'Commençons par remplir le formulaire suivant.',
      'it': 'Iniziamo compilando il seguente modulo.',
      'ja': 'まずは次のフォームに記入してみましょう。',
      'pt': 'Vamos começar preenchendo o seguinte formulário.',
    },
    'hk7irhyk': {
      'es': 'Correo',
      'ar': 'بريد',
      'de': 'Post',
      'en': 'Mail',
      'fr': 'Mail',
      'it': 'Posta',
      'ja': '郵便',
      'pt': 'Correspondência',
    },
    'e63kig46': {
      'es': 'Contraseña',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Password',
      'ja': 'パスワード',
      'pt': 'Senha',
    },
    'ozb99iw2': {
      'es': 'Confirmar Contraseña',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Passwort bestätigen',
      'en': 'Confirm Password',
      'fr': 'Confirmez le mot de passe',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'pt': 'Confirme sua senha',
    },
    '3u80jm1o': {
      'es': 'Crear Cuenta',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'en': 'Create Account',
      'fr': 'Créer un compte',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
    },
    '85i6efbq': {
      'es': '¿Ya tiene una cuenta? ',
      'ar': 'هل لديك حساب بالفعل؟',
      'de': 'Haben Sie bereits ein Konto?',
      'en': 'Already have an account?',
      'fr': 'Avez-vous déjà un compte ?',
      'it': 'Hai già un account?',
      'ja': 'すでにアカウントをお持ちですか?',
      'pt': 'Você já tem uma conta?',
    },
    '3vx9vl1j': {
      'es': 'Inicia sesión aquí!!',
      'ar': 'تسجيل الدخول هنا!!',
      'de': 'Melden Sie sich hier an!!',
      'en': 'Sign in here!!',
      'fr': 'Connectez-vous ici !!',
      'it': 'Accedi qui!!',
      'ja': 'ここからログインしてください!!',
      'pt': 'Faça login aqui!!',
    },
    '1t3z7v1e': {
      'es': 'Opciones adicionales:',
      'ar': 'خيارات إضافية:',
      'de': 'Zusätzliche Optionen:',
      'en': 'Additional options:',
      'fr': 'Options supplémentaires :',
      'it': 'Opzioni aggiuntive:',
      'ja': '追加のオプション:',
      'pt': 'Opções adicionais:',
    },
    'k0ijmmol': {
      'es': 'Continuar con Google',
      'ar': 'تواصل مع جوجل',
      'de': 'Weiter mit Google',
      'en': 'Continue with Google',
      'fr': 'Continuer avec Google',
      'it': 'Continua con Google',
      'ja': 'Google を続ける',
      'pt': 'Continuar com o Google',
    },
    '0apf5s2q': {
      'es': 'Continuar con Teléfono',
      'ar': 'تواصل مع الهاتف',
      'de': 'Weiter mit Telefon',
      'en': 'Continue with Phone',
      'fr': 'Continuer avec Téléphone',
      'it': 'Continuare con Telefono',
      'ja': '電話で続ける',
      'pt': 'Continuar com telefone',
    },
    '0ihi3ar5': {
      'es': 'Continuar como anónimo',
      'ar': 'استمر كمجهول',
      'de': 'Bleiben Sie weiterhin anonym',
      'en': 'Continue as anonymous',
      'fr': 'Continuer en anonyme',
      'it': 'Continua come anonimo',
      'ja': '匿名で続行',
      'pt': 'Continuar como anônimo',
    },
    'z0t1lmei': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // auth_3_Login
  {
    '5y6lvejr': {
      'es': 'Inicio de sesión',
      'ar': 'تسجيل الدخول',
      'de': 'Login',
      'en': 'Login',
      'fr': 'Se connecter',
      'it': 'Login',
      'ja': 'ログイン',
      'pt': 'Conecte-se',
    },
    'bimn5f2h': {
      'es': 'Empecemos rellenando el siguiente formulario.',
      'ar': 'لنبدأ بملء النموذج التالي.',
      'de': 'Beginnen wir mit dem Ausfüllen des folgenden Formulars.',
      'en': 'Let\'s get started by filling out the following form.',
      'fr': 'Commençons par remplir le formulaire suivant.',
      'it': 'Iniziamo compilando il seguente modulo.',
      'ja': 'まずは次のフォームに記入してみましょう。',
      'pt': 'Vamos começar preenchendo o seguinte formulário.',
    },
    'htgsb162': {
      'es': 'Correo',
      'ar': 'بريد',
      'de': 'Post',
      'en': 'Mail',
      'fr': 'Mail',
      'it': 'Posta',
      'ja': '郵便',
      'pt': 'Correspondência',
    },
    '4xbnfsev': {
      'es': 'Contraseña',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Password',
      'ja': 'パスワード',
      'pt': 'Senha',
    },
    'p60qc4c8': {
      'es': 'Inicio de Sesión',
      'ar': 'تسجيل الدخول',
      'de': 'Login',
      'en': 'Login',
      'fr': 'Se connecter',
      'it': 'Login',
      'ja': 'ログイン',
      'pt': 'Conecte-se',
    },
    '40ttsz7h': {
      'es': '¿No tiene una cuenta? ',
      'ar': 'ليس لديك حساب؟',
      'de': 'Sie haben noch kein Konto?',
      'en': 'Don\'t have an account?',
      'fr': 'Vous n\'avez pas de compte ?',
      'it': 'Non hai un account?',
      'ja': 'アカウントをお持ちでない場合は、',
      'pt': 'Não tem uma conta?',
    },
    '8zwx3dz3': {
      'es': '¡Regístrese aquí!!',
      'ar': 'سجل هنا!!',
      'de': 'Registrieren Sie sich hier!!',
      'en': 'Register here!!',
      'fr': 'Inscrivez-vous ici !!',
      'it': 'Registrati qui!!',
      'ja': 'ここから登録してください!!',
      'pt': 'Cadastre-se aqui!!',
    },
    'ed3vukqq': {
      'es': 'Opciones adicionales:',
      'ar': 'خيارات إضافية:',
      'de': 'Zusätzliche Optionen:',
      'en': 'Additional options:',
      'fr': 'Options supplémentaires :',
      'it': 'Opzioni aggiuntive:',
      'ja': '追加のオプション:',
      'pt': 'Opções adicionais:',
    },
    '8a3uyztw': {
      'es': 'Continuar con Google',
      'ar': 'تواصل مع جوجل',
      'de': 'Weiter mit Google',
      'en': 'Continue with Google',
      'fr': 'Continuer avec Google',
      'it': 'Continua con Google',
      'ja': 'Google を続ける',
      'pt': 'Continuar com o Google',
    },
    'tj08c2ch': {
      'es': 'Continuar con Teléfono',
      'ar': 'تواصل مع الهاتف',
      'de': 'Weiter mit Telefon',
      'en': 'Continue with Phone',
      'fr': 'Continuer avec Téléphone',
      'it': 'Continuare con Telefono',
      'ja': '電話で続ける',
      'pt': 'Continuar com telefone',
    },
    'si8t2e2c': {
      'es': 'Continuar como anónimo',
      'ar': 'استمر كمجهول',
      'de': 'Bleiben Sie weiterhin anonym',
      'en': 'Continue as anonymous',
      'fr': 'Continuer en anonyme',
      'it': 'Continua come anonimo',
      'ja': '匿名で続行',
      'pt': 'Continuar como anônimo',
    },
    'ww4vgpqe': {
      'es': '¿Olvidaste tu contraseña? ',
      'ar': 'نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'en': 'Forgot your password?',
      'fr': 'Vous avez oublié votre mot de passe ?',
      'it': 'Hai dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'pt': 'Esqueceu sua senha?',
    },
    'kwt3id5l': {
      'es': '¡Cámbiala aquí!!',
      'ar': 'تغييره هنا!!',
      'de': 'Ändere es hier!!',
      'en': 'Change it here!!',
      'fr': 'Changez-le ici !!',
      'it': 'Cambialo qui!!',
      'ja': 'ここで変更します!!',
      'pt': 'Mude aqui!!',
    },
    '4galstjb': {
      'es': 'Forgot Password? ',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'en': 'Forgot Password?',
      'fr': 'Mot de passe oublié ?',
      'it': 'Ha dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'pt': 'Esqueceu sua senha?',
    },
    'ox6pc1jj': {
      'es': 'Reset It Now',
      'ar': 'أعد ضبطه الآن',
      'de': 'Setzen Sie es jetzt zurück',
      'en': 'Reset It Now',
      'fr': 'Réinitialisez-le maintenant',
      'it': 'Reimpostalo ora',
      'ja': '今すぐリセットしてください',
      'pt': 'Redefinir agora',
    },
    'n08cb4wz': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // chat_2_Details
  {
    '33ilr9f9': {
      'es': 'Chat de Grupo',
      'ar': 'دردشة جماعية',
      'de': 'Gruppenchat',
      'en': 'Group Chat',
      'fr': 'Discussion de groupe',
      'it': 'Chat di gruppo',
      'ja': 'グループチャット',
      'pt': 'Bate-papo em grupo',
    },
    'd0hz68cb': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // chat_2_main
  {
    'mzpid5ig': {
      'es': 'A continuación, sus chats y chats de grupo',
      'ar': 'فيما يلي الدردشات والمحادثات الجماعية الخاصة بك',
      'de': 'Nachfolgend finden Sie Ihre Chats und Gruppenchats',
      'en': 'Below are your chats and group chats',
      'fr':
          'Vous trouverez ci-dessous vos discussions et discussions de groupe',
      'it': 'Di seguito sono riportate le tue chat e le chat di gruppo',
      'ja': '以下はあなたのチャットとグループチャットです',
      'pt': 'Abaixo estão seus bate-papos e bate-papos em grupo',
    },
    '9623vpi3': {
      'es': 'Chat en grupo',
      'ar': 'دردشة جماعية',
      'de': 'Gruppenchat',
      'en': 'Group chat',
      'fr': 'discussion de groupe',
      'it': 'chiacchierata di gruppo',
      'ja': 'グループチャット',
      'pt': 'bate-papo em grupo',
    },
    'lbkxmx7b': {
      'es': 'Mis Chats',
      'ar': 'دردشاتي',
      'de': 'Meine Chats',
      'en': 'My Chats',
      'fr': 'Mes discussions',
      'it': 'Le mie chat',
      'ja': '私のチャット',
      'pt': 'Meus bate-papos',
    },
    '00hyzoly': {
      'es': '__',
      'ar': '__',
      'de': '__',
      'en': '__',
      'fr': '__',
      'it': '__',
      'ja': '__',
      'pt': '__',
    },
  },
  // chat_2_InviteUsers
  {
    '9mj8ubun': {
      'es': 'Invitar a amigos',
      'ar': 'دعوة الأصدقاء',
      'de': 'Freunde einladen',
      'en': 'Invite friends',
      'fr': 'Inviter des amis',
      'it': 'Invita amici',
      'ja': '友達を招待する',
      'pt': 'Convide amigos',
    },
    's1pqna5x': {
      'es': 'Selección',
      'ar': 'اختيار',
      'de': 'Auswahl',
      'en': 'Selection',
      'fr': 'Sélection',
      'it': 'Selezione',
      'ja': '選択',
      'pt': 'Seleção',
    },
    'c3wolth3': {
      'es': 'Invitar Amigos',
      'ar': 'دعوة الأصدقاء',
      'de': 'Freunde einladen',
      'en': 'Invite Friends',
      'fr': 'Inviter des amis',
      'it': 'Invita amici',
      'ja': '友達を招待する',
      'pt': 'Convide amigos',
    },
    'iw8yq3r5': {
      'es': 'Seleccione los usuarios de abajo para iniciar un chat.',
      'ar': 'حدد المستخدمين أدناه لبدء الدردشة.',
      'de': 'Wählen Sie unten die Benutzer aus, um einen Chat zu starten.',
      'en': 'Select the users below to start a chat.',
      'fr':
          'Sélectionnez les utilisateurs ci-dessous pour démarrer une discussion.',
      'it': 'Seleziona gli utenti qui sotto per avviare una chat.',
      'ja': 'チャットを開始するには、以下のユーザーを選択してください。',
      'pt': 'Selecione os usuários abaixo para iniciar um chat.',
    },
    'derid691': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // image_Details
  {
    'jtth790f': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // Profile
  {
    '1ez5v0fu': {
      'es': 'Editar Perfil',
      'ar': 'تحرير الملف الشخصي',
      'de': 'Profil bearbeiten',
      'en': 'Edit Profile',
      'fr': 'Modifier le profil',
      'it': 'Modifica profilo',
      'ja': 'プロフィールの編集',
      'pt': 'Editar perfil',
    },
    'e0yxdnv5': {
      'es': 'Menu videos',
      'ar': 'فيديوهات القائمة',
      'de': 'Menüvideos',
      'en': 'Menu videos',
      'fr': 'Vidéos des menus',
      'it': 'Video del menù',
      'ja': 'メニュー動画',
      'pt': 'Vídeos do cardápio',
    },
    'v5321jog': {
      'es': 'Chat',
      'ar': 'محادثة',
      'de': 'Chatten',
      'en': 'Chat',
      'fr': 'Chat',
      'it': 'Chiacchierata',
      'ja': 'チャット',
      'pt': 'Bater papo',
    },
    'hr5oqq0e': {
      'es': 'Conexiones',
      'ar': 'اتصالات',
      'de': 'Verbindungen',
      'en': 'Connections',
      'fr': 'Relations',
      'it': 'Connessioni',
      'ja': '接続',
      'pt': 'Conexões',
    },
    'kxj89y2i': {
      'es': 'Mi Perfil',
      'ar': 'ملفي الشخصي',
      'de': 'Mein Profil',
      'en': 'My Profile',
      'fr': 'Mon profil',
      'it': 'Il mio profilo',
      'ja': '私のプロフィール',
      'pt': 'Meu perfil',
    },
    'vhxane65': {
      'es': 'Visión Mundial',
      'ar': 'الرؤية العالمية',
      'de': 'Weltvision',
      'en': 'World Vision',
      'fr': 'Vision mondiale',
      'it': 'Visione del mondo',
      'ja': 'ワールドビジョン',
      'pt': 'Visão Mundial',
    },
    'm58kid2z': {
      'es': 'Cerrar Sesión',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'en': 'Close Session',
      'fr': 'Se déconnecter',
      'it': 'Disconnessione',
      'ja': 'サインアウト',
      'pt': 'Sair',
    },
    'yslh57ib': {
      'es': '__',
      'ar': '__',
      'de': '__',
      'en': '__',
      'fr': '__',
      'it': '__',
      'ja': '__',
      'pt': '__',
    },
  },
  // profile_Main
  {
    'fye8ii3s': {
      'es': 'Información de mi cuenta',
      'ar': 'معلومات حسابي',
      'de': 'Meine Kontoinformationen',
      'en': 'My account information',
      'fr': 'Informations sur mon compte',
      'it': 'Le informazioni del mio account',
      'ja': '私のアカウント情報',
      'pt': 'Informações da minha conta',
    },
    'rzb2r5yd': {
      'es': 'Subir contenido exclusivo',
      'ar': 'تحميل المحتوى الحصري',
      'de': 'Laden Sie exklusive Inhalte hoch',
      'en': 'Upload exclusive content',
      'fr': 'Téléchargez du contenu exclusif',
      'it': 'Carica contenuti esclusivi',
      'ja': '限定コンテンツをアップロードする',
      'pt': 'Envie conteúdo exclusivo',
    },
    'lgfc1ip6': {
      'es': 'Editar Perfil',
      'ar': 'تحرير الملف الشخصي',
      'de': 'Profil bearbeiten',
      'en': 'Edit Profile',
      'fr': 'Modifier le profil',
      'it': 'Modifica profilo',
      'ja': 'プロフィールの編集',
      'pt': 'Editar perfil',
    },
    'lz8s6yhy': {
      'es': 'Soporte',
      'ar': 'واسطة',
      'de': 'Medium',
      'en': 'Medium',
      'fr': 'Moyen',
      'it': 'Medio',
      'ja': '中くらい',
      'pt': 'Médio',
    },
    '3i2x5cp4': {
      'es': 'Configuraciones de la cuenta',
      'ar': 'إعدادات الحساب',
      'de': 'Kontoeinstellungen',
      'en': 'account settings',
      'fr': 'paramètres du compte',
      'it': 'impostazioni dell\'account',
      'ja': 'アカウント設定',
      'pt': 'configurações de Conta',
    },
    'b161vqht': {
      'es': 'Claro',
      'ar': 'واضح',
      'de': 'Klar',
      'en': 'Clear',
      'fr': 'Clair',
      'it': 'Chiaro',
      'ja': 'クリア',
      'pt': 'Claro',
    },
    'psa31ysa': {
      'es': 'Oscuro',
      'ar': 'مظلم',
      'de': 'Dunkel',
      'en': 'Dark',
      'fr': 'Sombre',
      'it': 'Buio',
      'ja': '暗い',
      'pt': 'Escuro',
    },
    '3wonbohs': {
      'es': 'Cerrar Sesión',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'en': 'Close Session',
      'fr': 'Se déconnecter',
      'it': 'Disconnessione',
      'ja': 'サインアウト',
      'pt': 'Sair',
    },
    '42wamqng': {
      'es': 'Mi Perfil',
      'ar': 'ملفي الشخصي',
      'de': 'Mein Profil',
      'en': 'My Profile',
      'fr': 'Mon profil',
      'it': 'Il mio profilo',
      'ja': '私のプロフィール',
      'pt': 'Meu perfil',
    },
    'bluku9wo': {
      'es': 'Editar Perfil',
      'ar': 'تحرير الملف الشخصي',
      'de': 'Profil bearbeiten',
      'en': 'Edit Profile',
      'fr': 'Modifier le profil',
      'it': 'Modifica profilo',
      'ja': 'プロフィールの編集',
      'pt': 'Editar perfil',
    },
    'oxonbc8u': {
      'es': 'Menu videos',
      'ar': 'فيديوهات القائمة',
      'de': 'Menüvideos',
      'en': 'Menu videos',
      'fr': 'Vidéos des menus',
      'it': 'Video del menù',
      'ja': 'メニュー動画',
      'pt': 'Vídeos do cardápio',
    },
    'haqydqcn': {
      'es': 'Chat',
      'ar': 'محادثة',
      'de': 'Chatten',
      'en': 'Chat',
      'fr': 'Chat',
      'it': 'Chiacchierata',
      'ja': 'チャット',
      'pt': 'Bater papo',
    },
    'vwqilt8u': {
      'es': 'Conexiones',
      'ar': 'اتصالات',
      'de': 'Verbindungen',
      'en': 'Connections',
      'fr': 'Relations',
      'it': 'Connessioni',
      'ja': '接続',
      'pt': 'Conexões',
    },
    'wl0a1lfh': {
      'es': 'Mi Perfil',
      'ar': 'ملفي الشخصي',
      'de': 'Mein Profil',
      'en': 'My Profile',
      'fr': 'Mon profil',
      'it': 'Il mio profilo',
      'ja': '私のプロフィール',
      'pt': 'Meu perfil',
    },
    '6k6oiaf2': {
      'es': 'Visión Mundial',
      'ar': 'الرؤية العالمية',
      'de': 'Weltvision',
      'en': 'World Vision',
      'fr': 'Vision mondiale',
      'it': 'Visione del mondo',
      'ja': 'ワールドビジョン',
      'pt': 'Visão Mundial',
    },
    '6nd9xu0o': {
      'es': 'Cerrar Sesión',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'en': 'Close Session',
      'fr': 'Se déconnecter',
      'it': 'Disconnessione',
      'ja': 'サインアウト',
      'pt': 'Sair',
    },
    '7arefi65': {
      'es': '__',
      'ar': '__',
      'de': '__',
      'en': '__',
      'fr': '__',
      'it': '__',
      'ja': '__',
      'pt': '__',
    },
  },
  // profile_Settings
  {
    'w0alhgdq': {
      'es': 'Configuraciones de la cuenta',
      'ar': 'إعدادات الحساب',
      'de': 'Kontoeinstellungen',
      'en': 'account settings',
      'fr': 'paramètres du compte',
      'it': 'impostazioni dell\'account',
      'ja': 'アカウント設定',
      'pt': 'configurações de Conta',
    },
    'nicwhctv': {
      'es': 'Evalúe sus opciones a continuación.',
      'ar': 'قم بتقييم خياراتك أدناه.',
      'de': 'Bewerten Sie unten Ihre Optionen.',
      'en': 'Evaluate your options below.',
      'fr': 'Évaluez vos options ci-dessous.',
      'it': 'Valuta le tue opzioni di seguito.',
      'ja': '以下のオプションを評価してください。',
      'pt': 'Avalie suas opções abaixo.',
    },
    'ckcu2jfm': {
      'es': 'Empezando',
      'ar': 'ابدء',
      'de': 'Erste Schritte',
      'en': 'Getting started',
      'fr': 'Commencer',
      'it': 'Iniziare',
      'ja': 'はじめる',
      'pt': 'Começando',
    },
    'j3ok5m2v': {
      'es': 'Sobre nosotros',
      'ar': 'معلومات عنا',
      'de': 'Über uns',
      'en': 'About us',
      'fr': 'À propos de nous',
      'it': 'Chi siamo',
      'ja': '私たちについて',
      'pt': 'Sobre nós',
    },
    'x6nwblra': {
      'es': 'Ayuda',
      'ar': 'يساعد',
      'de': 'Hilfe',
      'en': 'Aid',
      'fr': 'Aide',
      'it': 'Aiuto',
      'ja': '援助',
      'pt': 'Ajuda',
    },
    '8rlvkqam': {
      'es': 'Política de privacidad',
      'ar': 'سياسة الخصوصية',
      'de': 'Datenschutzrichtlinie',
      'en': 'Privacy Policy',
      'fr': 'politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'pt': 'política de Privacidade',
    },
    'daaa99om': {
      'es': 'Términos  & Condiciones',
      'ar': 'الشروط والأحكام',
      'de': 'Allgemeine Geschäftsbedingungen',
      'en': 'Terms & Conditions',
      'fr': 'Conditions générales',
      'it': 'Termini e condizioni',
      'ja': '利用規約',
      'pt': 'Termos e Condições',
    },
    '6ao4a0og': {
      'es': 'Siga con nosotros',
      'ar': 'تابعنا',
      'de': 'Folgen Sie uns',
      'en': 'Follow us',
      'fr': 'Suivez-nous',
      'it': 'Seguici',
      'ja': '私たちに従ってください',
      'pt': 'Siga-nos',
    },
    'lx2c8zqj': {
      'es': 'Versiones de la aplicación',
      'ar': 'إصدارات التطبيق',
      'de': 'Anwendungsversionen',
      'en': 'Application versions',
      'fr': 'Versions des applications',
      'it': 'Versioni dell\'applicazione',
      'ja': 'アプリケーションのバージョン',
      'pt': 'Versões do aplicativo',
    },
    'ov48wnzo': {
      'es': 'v0.0.1',
      'ar': 'v0.0.1',
      'de': 'v0.0.1',
      'en': 'v0.0.1',
      'fr': 'v0.0.1',
      'it': 'v0.0.1',
      'ja': 'v0.0.1',
      'pt': 'v0.0.1',
    },
    'aze1o4mj': {
      'es': 'CerrarSesión',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'en': 'Logout',
      'fr': 'Déconnexion',
      'it': 'Esci',
      'ja': 'ログアウト',
      'pt': 'Sair',
    },
    'blf46v40': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // profile_ChangePassword
  {
    'yeb0j5uo': {
      'es': 'Atrás',
      'ar': 'خلف',
      'de': 'Zurück',
      'en': 'Back',
      'fr': 'Dos',
      'it': 'Indietro',
      'ja': '戻る',
      'pt': 'Voltar',
    },
    'bdu7fifm': {
      'es': 'Restablecer contraseña',
      'ar': 'إعادة تعيين كلمة المرور',
      'de': 'Passwort zurücksetzen',
      'en': 'Reset password',
      'fr': 'Réinitialiser le mot de passe',
      'it': 'Reimposta la password',
      'ja': 'パスワードをリセットする',
      'pt': 'Redefinir senha',
    },
    'b610m3mc': {
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña; ingrese el correo electrónico asociado con su cuenta a continuación.',
      'ar':
          'سنرسل إليك بريدًا إلكترونيًا يحتوي على رابط لإعادة تعيين كلمة المرور الخاصة بك؛ أدخل البريد الإلكتروني المرتبط بحسابك أدناه.',
      'de':
          'Wir senden Ihnen eine E-Mail mit einem Link zum Zurücksetzen Ihres Passworts; Geben Sie unten die mit Ihrem Konto verknüpfte E-Mail-Adresse ein.',
      'en':
          'We\'ll send you an email with a link to reset your password; enter the email associated with your account below.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe ; Entrez ci-dessous l\'e-mail associé à votre compte.',
      'it':
          'Ti invieremo un\'e-mail con un collegamento per reimpostare la password; Inserisci qui sotto l\'e-mail associata al tuo account.',
      'ja': 'パスワードをリセットするためのリンクを記載した電子メールを送信します。以下にアカウントに関連付けられたメールアドレスを入力します。',
      'pt':
          'Enviaremos um e-mail com um link para redefinir sua senha; Digite o e-mail associado à sua conta abaixo.',
    },
    '1gmr0zk3': {
      'es': 'Correo electrónico',
      'ar': 'بريد إلكتروني',
      'de': 'E-Mail',
      'en': 'Email',
      'fr': 'E-mail',
      'it': 'E-mail',
      'ja': '電子メール',
      'pt': 'E-mail',
    },
    '91eavmz7': {
      'es': 'Ingresa tu correo...',
      'ar': 'أدخل بريدك الإلكتروني...',
      'de': 'Geben Sie Ihre E-Mail-Adresse ein...',
      'en': 'Enter your email...',
      'fr': 'Entrez votre email...',
      'it': 'Inserisci la tua email...',
      'ja': 'メールアドレスを入力してください...',
      'pt': 'Digite seu e-mail...',
    },
    '83t1oz3c': {
      'es': 'Restablecer',
      'ar': 'يعيد',
      'de': 'Wiederherstellen',
      'en': 'Restore',
      'fr': 'Restaurer',
      'it': 'Ripristinare',
      'ja': '復元する',
      'pt': 'Restaurar',
    },
    'sefn4tn8': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // profile_Edit
  {
    '6d2884tg': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // profile_Create
  {
    'czywqcgl': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // ListMemberSearch
  {
    'o0dd05pv': {
      'es': 'Inversores',
      'ar': 'المستثمرين',
      'de': 'Investoren',
      'en': 'Investors',
      'fr': 'Investisseurs',
      'it': 'Investitori',
      'ja': '投資家',
      'pt': 'Investidores',
    },
    'pd8kccye': {
      'es': 'Buscar inversores...',
      'ar': 'البحث عن المستثمرين...',
      'de': 'Suche nach Investoren...',
      'en': 'Looking for investors...',
      'fr': 'Recherche d\'investisseurs...',
      'it': 'Cerca investitori...',
      'ja': '投資家を探す...',
      'pt': 'Procure investidores...',
    },
    'uthkar3x': {
      'es': 'Inversores VIP',
      'ar': 'كبار المستثمرين',
      'de': 'VIP-Investoren',
      'en': 'VIP Investors',
      'fr': 'Investisseurs VIP',
      'it': 'Investitori VIP',
      'ja': 'VIP投資家',
      'pt': 'Investidores VIP',
    },
    '2tz1f68q': {
      'es': 'Inversores',
      'ar': 'المستثمرين',
      'de': 'Investoren',
      'en': 'Investors',
      'fr': 'Investisseurs',
      'it': 'Investitori',
      'ja': '投資家',
      'pt': 'Investidores',
    },
    'uhxc85k6': {
      'es': 'Ver mas',
      'ar': 'شاهد المزيد',
      'de': 'Mehr sehen',
      'en': 'See more',
      'fr': 'Voir plus',
      'it': 'Vedi di più',
      'ja': 'もっと見る',
      'pt': 'Ver mais',
    },
    '7gphl2lm': {
      'es': 'Vista',
      'ar': 'منظر',
      'de': 'Sicht',
      'en': 'View',
      'fr': 'Voir',
      'it': 'Visualizzazione',
      'ja': 'ビュー',
      'pt': 'Visualizar',
    },
    'uwm1t08r': {
      'es': 'miembro',
      'ar': 'عضو',
      'de': 'Mitglied',
      'en': 'member',
      'fr': 'membre',
      'it': 'membro',
      'ja': 'メンバー',
      'pt': 'membro',
    },
  },
  // listviewHome
  {
    'b0c9s98e': {
      'es': 'Editar Perfil',
      'ar': 'تحرير الملف الشخصي',
      'de': 'Profil bearbeiten',
      'en': 'Edit Profile',
      'fr': 'Modifier le profil',
      'it': 'Modifica profilo',
      'ja': 'プロフィールの編集',
      'pt': 'Editar perfil',
    },
    'ekav0ajv': {
      'es': 'Menu videos',
      'ar': 'فيديوهات القائمة',
      'de': 'Menüvideos',
      'en': 'Menu videos',
      'fr': 'Vidéos des menus',
      'it': 'Video del menù',
      'ja': 'メニュー動画',
      'pt': 'Vídeos do cardápio',
    },
    '76yklwfx': {
      'es': 'Chat',
      'ar': 'محادثة',
      'de': 'Chatten',
      'en': 'Chat',
      'fr': 'Chat',
      'it': 'Chiacchierata',
      'ja': 'チャット',
      'pt': 'Bater papo',
    },
    '44z1rmq7': {
      'es': 'Conexiones',
      'ar': 'اتصالات',
      'de': 'Verbindungen',
      'en': 'Connections',
      'fr': 'Relations',
      'it': 'Connessioni',
      'ja': '接続',
      'pt': 'Conexões',
    },
    'd7f3ectu': {
      'es': 'Mi Perfil',
      'ar': 'ملفي الشخصي',
      'de': 'Mein Profil',
      'en': 'My Profile',
      'fr': 'Mon profil',
      'it': 'Il mio profilo',
      'ja': '私のプロフィール',
      'pt': 'Meu perfil',
    },
    'hkjhia0y': {
      'es': 'Visión Mundial',
      'ar': 'الرؤية العالمية',
      'de': 'Weltvision',
      'en': 'World Vision',
      'fr': 'Vision mondiale',
      'it': 'Visione del mondo',
      'ja': 'ワールドビジョン',
      'pt': 'Visão Mundial',
    },
    'gnzfnbun': {
      'es': 'Selector de idiomas',
      'ar': 'محدد اللغة',
      'de': 'Sprachauswahl',
      'en': 'Language selector',
      'fr': 'Sélecteur de langue',
      'it': 'Selettore della lingua',
      'ja': '言語セレクター',
      'pt': 'Seletor de idioma',
    },
    '64ambkiu': {
      'es': 'Seguridad',
      'ar': 'حماية',
      'de': 'Sicherheit',
      'en': 'Security',
      'fr': 'Sécurité',
      'it': 'Sicurezza',
      'ja': '安全',
      'pt': 'Segurança',
    },
    'hdml80hn': {
      'es': 'Cerrar Sesión',
      'ar': 'تسجيل الخروج',
      'de': 'Abmelden',
      'en': 'Close Session',
      'fr': 'Se déconnecter',
      'it': 'Disconnessione',
      'ja': 'サインアウト',
      'pt': 'Sair',
    },
    '6vvtstci': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // DetallesMiembros
  {
    '4b3x4u2k': {
      'es': 'Network',
      'ar': 'شبكة',
      'de': 'Netzwerk',
      'en': 'Network',
      'fr': 'réseau',
      'it': 'rete',
      'ja': 'ネットワーク',
      'pt': 'rede',
    },
    'dsrzz6jw': {
      'es': 'Network:',
      'ar': 'شبكة:',
      'de': 'Netzwerk:',
      'en': 'Network:',
      'fr': 'Réseau:',
      'it': 'Rete:',
      'ja': 'ネットワーク：',
      'pt': 'Rede:',
    },
    'epoak4lc': {
      'es': 'Reacciones',
      'ar': 'ردود الفعل',
      'de': 'Reaktionen',
      'en': 'Reactions',
      'fr': 'Réactions',
      'it': 'Reazioni',
      'ja': '反応',
      'pt': 'Reações',
    },
    'sm38b0o4': {
      'es': 'Seguidores',
      'ar': 'المتابعون',
      'de': 'Anhänger',
      'en': 'Followers',
      'fr': 'Abonnés',
      'it': 'Seguaci',
      'ja': 'フォロワー',
      'pt': 'Seguidores',
    },
    'd6djbrjs': {
      'es': 'Siguiendo',
      'ar': 'التالي',
      'de': 'Nachfolgend',
      'en': 'Following',
      'fr': 'Suivant',
      'it': 'Seguente',
      'ja': '続く',
      'pt': 'Seguindo',
    },
    'xy5zv279': {
      'es': 'Momentum',
      'ar': 'دَفعَة',
      'de': 'Schwung',
      'en': 'Momentum',
      'fr': 'Élan',
      'it': 'Slancio',
      'ja': '勢い',
      'pt': 'Momento',
    },
    'zbh39ndw': {
      'es': 'Siguiendo',
      'ar': 'التالي',
      'de': 'Nachfolgend',
      'en': 'Following',
      'fr': 'Suivant',
      'it': 'Seguente',
      'ja': '続く',
      'pt': 'Seguindo',
    },
    'qsq7mhhj': {
      'es': 'Consejos de inversión',
      'ar': 'نصائح للاستثمار',
      'de': 'Anlagetipps',
      'en': 'Investment Tips',
      'fr': 'Conseils d\'investissement',
      'it': 'Consigli per gli investimenti',
      'ja': '投資のヒント',
      'pt': 'Dicas de investimento',
    },
    'c1fyq9gy': {
      'es': '63 artículos',
      'ar': '63 مادة',
      'de': '63 Artikel',
      'en': '63 articles',
      'fr': '63 articles',
      'it': '63 articoli',
      'ja': '63 件',
      'pt': '63 itens',
    },
    '7hdmn0ra': {
      'es': 'Pasado',
      'ar': 'ماضي',
      'de': 'Vergangenheit',
      'en': 'Past',
      'fr': 'Passé',
      'it': 'Passato',
      'ja': '過去',
      'pt': 'Passado',
    },
    'zzhr2jdv': {
      'es': 'Presente',
      'ar': 'حاضر',
      'de': 'Gegenwärtig',
      'en': 'Present',
      'fr': 'Présent',
      'it': 'Presente',
      'ja': '現在',
      'pt': 'Presente',
    },
    'r56ze9zd': {
      'es': 'Futuro',
      'ar': 'مستقبل',
      'de': 'Zukunft',
      'en': 'Future',
      'fr': 'Avenir',
      'it': 'Futuro',
      'ja': '未来',
      'pt': 'Futuro',
    },
    'y51uo6y7': {
      'es': 'Detailes',
      'ar': 'تفاصيل',
      'de': 'Einzelheiten',
      'en': 'Details',
      'fr': 'Détails',
      'it': 'Dettagli',
      'ja': '詳細',
      'pt': 'Detalhes',
    },
    'ey3yppou': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // myProfile
  {
    'h74sgoec': {
      'es': 'Network:',
      'ar': 'شبكة:',
      'de': 'Netzwerk:',
      'en': 'Network:',
      'fr': 'Réseau:',
      'it': 'Rete:',
      'ja': 'ネットワーク：',
      'pt': 'Rede:',
    },
    '2sl59kv3': {
      'es': 'Network',
      'ar': 'شبكة',
      'de': 'Netzwerk',
      'en': 'Network',
      'fr': 'réseau',
      'it': 'rete',
      'ja': 'ネットワーク',
      'pt': 'rede',
    },
    '78ezk5r6': {
      'es': 'Reacciones',
      'ar': 'ردود الفعل',
      'de': 'Reaktionen',
      'en': 'Reactions',
      'fr': 'Réactions',
      'it': 'Reazioni',
      'ja': '反応',
      'pt': 'Reações',
    },
    'l9kvjcd9': {
      'es': 'Seguidores',
      'ar': 'المتابعون',
      'de': 'Anhänger',
      'en': 'Followers',
      'fr': 'Abonnés',
      'it': 'Seguaci',
      'ja': 'フォロワー',
      'pt': 'Seguidores',
    },
    '5mq1ymxh': {
      'es': 'Siguiendo',
      'ar': 'التالي',
      'de': 'Nachfolgend',
      'en': 'Following',
      'fr': 'Suivant',
      'it': 'Seguente',
      'ja': '続く',
      'pt': 'Seguindo',
    },
    'dgw7bhl0': {
      'es': 'Momentum',
      'ar': 'دَفعَة',
      'de': 'Schwung',
      'en': 'Momentum',
      'fr': 'Élan',
      'it': 'Slancio',
      'ja': '勢い',
      'pt': 'Momento',
    },
    'gx4xvhg7': {
      'es': 'Consejos de inversión',
      'ar': 'نصائح للاستثمار',
      'de': 'Anlagetipps',
      'en': 'Investment Tips',
      'fr': 'Conseils d\'investissement',
      'it': 'Consigli per gli investimenti',
      'ja': '投資のヒント',
      'pt': 'Dicas de investimento',
    },
    'bm2w6rxb': {
      'es': '63 artículos',
      'ar': '63 مادة',
      'de': '63 Artikel',
      'en': '63 articles',
      'fr': '63 articles',
      'it': '63 articoli',
      'ja': '63 件',
      'pt': '63 itens',
    },
    'locvhz1p': {
      'es': 'Pasado',
      'ar': 'ماضي',
      'de': 'Vergangenheit',
      'en': 'Past',
      'fr': 'Passé',
      'it': 'Passato',
      'ja': '過去',
      'pt': 'Passado',
    },
    '52x66fft': {
      'es': 'Presente',
      'ar': 'حاضر',
      'de': 'Gegenwärtig',
      'en': 'Present',
      'fr': 'Présent',
      'it': 'Presente',
      'ja': '現在',
      'pt': 'Presente',
    },
    'ge6cwmv1': {
      'es': 'Futuro',
      'ar': 'مستقبل',
      'de': 'Zukunft',
      'en': 'Future',
      'fr': 'Avenir',
      'it': 'Futuro',
      'ja': '未来',
      'pt': 'Futuro',
    },
    'fwplnbuq': {
      'es': 'Mi Perfil',
      'ar': 'ملفي الشخصي',
      'de': 'Mein Profil',
      'en': 'My Profile',
      'fr': 'Mon profil',
      'it': 'Il mio profilo',
      'ja': '私のプロフィール',
      'pt': 'Meu perfil',
    },
    'agvljy4i': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // mapLocation
  {
    '8u445t4d': {
      'es': 'Chicago',
      'ar': 'شيكاغو',
      'de': 'Chicago',
      'en': 'Chicago',
      'fr': 'Chicago',
      'it': 'Chicago',
      'ja': 'シカゴ',
      'pt': 'Chicago',
    },
    'qg7xxo4m': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // ContenidoExclusivo
  {
    'ym50b74y': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // ingresarPhone
  {
    'pyc8gded': {
      'es': 'Atrás',
      'ar': 'خلف',
      'de': 'Zurück',
      'en': 'Back',
      'fr': 'Dos',
      'it': 'Indietro',
      'ja': '戻る',
      'pt': 'Voltar',
    },
    'xlp0i3gh': {
      'es': 'Ingresa tu telefono',
      'ar': 'أدخل هاتفك',
      'de': 'Geben Sie Ihr Telefon ein',
      'en': 'Enter your phone number',
      'fr': 'Entrez votre téléphone',
      'it': 'Inserisci il tuo telefono',
      'ja': '電話番号を入力してください',
      'pt': 'Digite seu telefone',
    },
    '0iuwa6jl': {
      'es':
          'Para iniciar sesión con tu teléfono, ingrésalo y recibirás un SMS con el código de verificación',
      'ar':
          'لتسجيل الدخول بهاتفك، قم بإدخاله وستصلك رسالة نصية تحتوي على رمز التحقق',
      'de':
          'Um sich mit Ihrem Telefon anzumelden, geben Sie es ein und Sie erhalten eine SMS mit dem Bestätigungscode',
      'en':
          'To log in with your phone, enter it and you will receive an SMS with the verification code',
      'fr':
          'Pour vous connecter avec votre téléphone, entrez-le et vous recevrez un SMS avec le code de vérification',
      'it':
          'Per accedere con il tuo telefono inseriscilo e riceverai un SMS con il codice di verifica',
      'ja': '携帯電話でログインするには、それを入力すると、確認コードが記載された SMS が届きます。',
      'pt':
          'Para fazer login com seu telefone, digite-o e você receberá um SMS com o código de verificação',
    },
    '07cyt33o': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    '8vav84zw': {
      'es': 'Ingresa tu teléfono... +1 321 987 6543',
      'ar': 'أدخل هاتفك...',
      'de': 'Geben Sie Ihr Telefon ein...',
      'en': 'Enter your phone number...',
      'fr': 'Entrez votre téléphone...',
      'it': 'Inserisci il tuo telefono...',
      'ja': '電話番号を入力してください...',
      'pt': 'Digite seu telefone...',
    },
    'wsqh942g': {
      'es': 'Enviar número',
      'ar': 'أرسل الرقم',
      'de': 'Nummer senden',
      'en': 'Send number',
      'fr': 'Envoyer le numéro',
      'it': 'Invia numero',
      'ja': '番号を送信する',
      'pt': 'Enviar número',
    },
    't5o5g5oe': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // ingresarPinCode
  {
    'e42og9eg': {
      'es': 'Ingrese su codigo',
      'ar': 'أدخل الرمز الخاص بك',
      'de': 'Geben Sie Ihren Code ein',
      'en': 'Enter your code',
      'fr': 'Entrez votre code',
      'it': 'Inserisci il tuo codice',
      'ja': 'コードを入力してください',
      'pt': 'Digite seu código',
    },
    'nz9pvc9c': {
      'es': 'Ingresa el código de verificación enviado por SMS para continuar.',
      'ar': 'أدخل رمز التحقق المرسل عبر الرسائل النصية القصيرة للمتابعة.',
      'de':
          'Geben Sie den per SMS gesendeten Bestätigungscode ein, um fortzufahren.',
      'en': 'Enter the verification code sent by SMS to continue.',
      'fr': 'Saisissez le code de vérification envoyé par SMS pour continuer.',
      'it': 'Inserisci il codice di verifica inviato via SMS per continuare.',
      'ja': '続行するには、SMS で送信された確認コードを入力してください。',
      'pt': 'Digite o código de verificação enviado por SMS para continuar.',
    },
    'ijt974lm': {
      'es': 'Cancelar',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Cancellare',
      'ja': 'キャンセル',
      'pt': 'Cancelar',
    },
    '05261zzp': {
      'es': 'Verificar codigo',
      'ar': 'التحقق من الرمز',
      'de': 'Code überprüfen',
      'en': 'Verify code',
      'fr': 'Vérifier le code',
      'it': 'Verifica il codice',
      'ja': 'コードを検証する',
      'pt': 'Verifique o código',
    },
    'xwgk65w3': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // Language
  {
    'i254bb74': {
      'es': 'Cambiar idioma',
      'ar': 'تغيير اللغة',
      'de': 'Sprache ändern',
      'en': 'Change language',
      'fr': 'Changer de langue',
      'it': 'Cambia lingua',
      'ja': '言語を変更する',
      'pt': 'Alterar idioma',
    },
    'nc2viugc': {
      'es': 'Cambiar idioma',
      'ar': 'تغيير اللغة',
      'de': 'Sprache ändern',
      'en': 'Change language',
      'fr': 'Changer de langue',
      'it': 'Cambia lingua',
      'ja': '言語を変更する',
      'pt': 'Alterar idioma',
    },
    'x6jo4b6x': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // Security
  {
    'hptbbu5i': {
      'es': 'Seguridad',
      'ar': 'حماية',
      'de': 'Sicherheit',
      'en': 'Security',
      'fr': 'Sécurité',
      'it': 'Sicurezza',
      'ja': '安全',
      'pt': 'Segurança',
    },
    'ybuhnqx5': {
      'es': 'Seguridad',
      'ar': 'حماية',
      'de': 'Sicherheit',
      'en': 'Security',
      'fr': 'Sécurité',
      'it': 'Sicurezza',
      'ja': '安全',
      'pt': 'Segurança',
    },
    're8tuon6': {
      'es': 'Capa de seguridad',
      'ar': 'طبقة الأمان',
      'de': 'Sicherheitsschicht',
      'en': 'Security layer',
      'fr': 'Couche de sécurité',
      'it': 'Livello di sicurezza',
      'ja': 'セキュリティ層',
      'pt': 'Camada de segurança',
    },
    '05cpqh36': {
      'es': 'Código PIN',
      'ar': 'رمز التعريف الشخصي',
      'de': 'PIN-Code',
      'en': 'PIN code',
      'fr': 'Code PIN',
      'it': 'Codice PIN',
      'ja': 'PINコード',
      'pt': 'Código PIN',
    },
    'tokymhdy': {
      'es': 'Identificación Biometrica',
      'ar': 'تحديد الهوية البيومترية',
      'de': 'Biometrische Identifizierung',
      'en': 'Biometric Identification',
      'fr': 'Identification biométrique',
      'it': 'Identificazione biometrica',
      'ja': '生体認証による識別',
      'pt': 'Identificação Biométrica',
    },
    'itbbmak3': {
      'es': 'Google Authenticator',
      'ar': 'أداة مصادقة جوجل',
      'de': 'Google Authenticator',
      'en': 'Google Authenticator',
      'fr': 'Authentificateur Google',
      'it': 'Autenticatore di Google',
      'ja': 'Google認証システム',
      'pt': 'Autenticador Google',
    },
    'sommqqrw': {
      'es': 'Cambiar código PIN',
      'ar': 'تغيير رمز PIN',
      'de': 'PIN-Code ändern',
      'en': 'Change PIN code',
      'fr': 'Changer le code PIN',
      'it': 'Cambia codice PIN',
      'ja': 'PINコードを変更する',
      'pt': 'Alterar código PIN',
    },
    'nr3pz2nf': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // pinCodeSet
  {
    'axnl4nqb': {
      'es': 'Establezca el código PIN de su aplicación',
      'ar': 'قم بتعيين رمز PIN للتطبيق الخاص بك',
      'de': 'Legen Sie Ihren App-PIN-Code fest',
      'en': 'Set your app PIN code',
      'fr': 'Définir le code PIN de votre application',
      'it': 'Imposta il codice PIN dell\'app',
      'ja': 'アプリのPINコードを設定する',
      'pt': 'Defina o código PIN do seu aplicativo',
    },
    'ynlhcblg': {
      'es': 'Agregue un número PIN para hacer su cuenta más segura.',
      'ar': 'أضف رقم PIN لجعل حسابك أكثر أمانًا.',
      'de': 'Fügen Sie eine PIN-Nummer hinzu, um Ihr Konto sicherer zu machen.',
      'en': 'Add a PIN number to make your account more secure.',
      'fr': 'Ajoutez un code PIN pour rendre votre compte plus sécurisé.',
      'it': 'Aggiungi un numero PIN per rendere il tuo account più sicuro.',
      'ja': 'PIN 番号を追加してアカウントの安全性を高めます。',
      'pt': 'Adicione um número PIN para tornar sua conta mais segura.',
    },
    '32gd19yk': {
      'es': 'Borrar',
      'ar': 'يمسح',
      'de': 'Löschen',
      'en': 'Delete',
      'fr': 'Supprimer',
      'it': 'Eliminare',
      'ja': '消去',
      'pt': 'Excluir',
    },
    '4wr7km68': {
      'es': 'Continue',
      'ar': 'يكمل',
      'de': 'Weitermachen',
      'en': 'Continue',
      'fr': 'Continuer',
      'it': 'Continuare',
      'ja': '続く',
      'pt': 'Continuar',
    },
    'iyikcdm5': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
  },
  // BiometricSet
  {
    'p1lcthmv': {
      'es': 'Establezca su Huella Dactilar',
      'ar': 'إنشاء بصمة الإصبع الخاصة بك',
      'de': 'Ermitteln Sie Ihren Fingerabdruck',
      'en': 'Set your Fingerprint',
      'fr': 'Établissez votre empreinte digitale',
      'it': 'Stabilisci la tua impronta digitale',
      'ja': '指紋を確立する',
      'pt': 'Estabeleça sua impressão digital',
    },
    '89k388fn': {
      'es': 'Please put your finger on the fingerprint scanner to get started.',
      'ar': 'يرجى وضع إصبعك على الماسح الضوئي لبصمات الأصابع للبدء.',
      'de':
          'Bitte legen Sie Ihren Finger auf den Fingerabdruckscanner, um zu beginnen.',
      'en': 'Please put your finger on the fingerprint scanner to get started.',
      'fr':
          'Veuillez mettre votre doigt sur le scanner d\'empreintes digitales pour commencer.',
      'it':
          'Per iniziare, metti il ​​dito sullo scanner delle impronte digitali.',
      'ja': '開始するには、指紋スキャナーに指を置いてください。',
      'pt': 'Coloque o dedo no leitor de impressão digital para começar.',
    },
    'auda4fbp': {
      'es': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'en': 'Home',
      'fr': 'Maison',
      'it': 'Casa',
      'ja': '家',
      'pt': 'Lar',
    },
    'kgjirwzz': {
      'es': 'You want to enable the biometric as your second security level?',
      'ar': 'هل تريد تمكين القياسات الحيوية كمستوى الأمان الثاني لديك؟',
      'de': 'Möchten Sie die Biometrie als zweite Sicherheitsstufe aktivieren?',
      'en':
          'Do you want to enable the biometric as your second security level?',
      'fr':
          'Souhaitez-vous activer la biométrie comme deuxième niveau de sécurité ?',
      'it': 'Vuoi abilitare la biometria come secondo livello di sicurezza?',
      'ja': '2 番目のセキュリティ レベルとして生体認証を有効にしますか?',
      'pt': 'Deseja habilitar a biometria como seu segundo nível de segurança?',
    },
  },
  // chat_DetailsOverlay
  {
    'abszyjf4': {
      'es': 'Detalles del Chat',
      'ar': 'تفاصيل الدردشة',
      'de': 'Chat-Details',
      'en': 'Chat Details',
      'fr': 'Détails du chat',
      'it': 'Dettagli della chat',
      'ja': 'チャットの詳細',
      'pt': 'Detalhes do bate-papo',
    },
    '5fg504zb': {
      'es': 'ID de chat de grupo: ',
      'ar': 'معرف الدردشة الجماعية:',
      'de': 'Gruppenchat-ID:',
      'en': 'Group Chat ID:',
      'fr': 'Identifiant de discussion de groupe :',
      'it': 'ID chat di gruppo:',
      'ja': 'グループチャットID:',
      'pt': 'ID do bate-papo em grupo:',
    },
    'qyfg6005': {
      'es': 'En este chat',
      'ar': 'في هذه الدردشة',
      'de': 'in diesem Chat',
      'en': 'In this chat',
      'fr': 'dans cette discussion',
      'it': 'in questa chiacchierata',
      'ja': 'このチャットで',
      'pt': 'neste bate-papo',
    },
    'hey24a39': {
      'es': 'Cerrar',
      'ar': 'يغلق',
      'de': 'Schließen',
      'en': 'Close',
      'fr': 'Fermer',
      'it': 'Vicino',
      'ja': '近い',
      'pt': 'Fechar',
    },
  },
  // chat_ThreadComponent
  {
    'dfgqz6k0': {
      'es': 'Empieza a escribir aquí...',
      'ar': 'ابدأ بالكتابة هنا...',
      'de': 'Beginnen Sie hier zu schreiben...',
      'en': 'Start writing here...',
      'fr': 'Commencez à écrire ici...',
      'it': 'Inizia a scrivere qui...',
      'ja': 'ここから書き始めてください...',
      'pt': 'Comece a escrever aqui...',
    },
    'j7tp7htg': {
      'es': 'Campo requerido',
      'ar': 'الحقل المطلوب',
      'de': 'Erforderliches Feld',
      'en': 'Required field',
      'fr': 'Champ obligatoire',
      'it': 'Campo obbligatorio',
      'ja': '必須フィールド',
      'pt': 'Campo obrigatório',
    },
    '2e8isfpj': {
      'es': 'Por favor elija una opción del menú desplegable',
      'ar': 'يرجى اختيار خيار من القائمة المنسدلة',
      'de': 'Bitte wählen Sie eine Option aus dem Dropdown-Menü',
      'en': 'Please choose an option from the drop-down menu',
      'fr': 'Veuillez choisir une option dans le menu déroulant',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンメニューからオプションを選択してください',
      'pt': 'Escolha uma opção no menu suspenso',
    },
  },
  // user_ListSmall
  {
    '5sv29nj4': {
      'es': 'Admin',
      'ar': 'مسؤل',
      'de': 'Admin',
      'en': 'Admin',
      'fr': 'Administrateur',
      'it': 'Ammin',
      'ja': '管理者',
      'pt': 'Administrador',
    },
  },
  // deleteDialog
  {
    'v3j2apwk': {
      'es': 'Opciones',
      'ar': 'خيارات',
      'de': 'Optionen',
      'en': 'Options',
      'fr': 'Possibilités',
      'it': 'Opzioni',
      'ja': 'オプション',
      'pt': 'Opções',
    },
    'ekigmo9n': {
      'es': 'Invitar Usuarios',
      'ar': 'دعوة المستخدمين',
      'de': 'Benutzer einladen',
      'en': 'Invite Users',
      'fr': 'Inviter des utilisateurs',
      'it': 'Invita utenti',
      'ja': 'ユーザーを招待する',
      'pt': 'Convidar usuários',
    },
    'gbdzek57': {
      'es': 'Eliminar Chat',
      'ar': 'حذف الدردشة',
      'de': 'Chat löschen',
      'en': 'Delete Chat',
      'fr': 'Supprimer le chat',
      'it': 'Elimina chat',
      'ja': 'チャットの削除',
      'pt': 'Excluir bate-papo',
    },
    'al48gg8d': {
      'es': 'Confirmar',
      'ar': 'يتأكد',
      'de': 'Bestätigen',
      'en': 'Confirm',
      'fr': 'Confirmer',
      'it': 'Confermare',
      'ja': '確認する',
      'pt': 'Confirmar',
    },
    'jpwub8ub': {
      'es': 'No puedes deshacer esta acción.',
      'ar': 'لا يمكنك التراجع عن هذا الإجراء.',
      'de': 'Sie können diese Aktion nicht rückgängig machen.',
      'en': 'You cannot undo this action.',
      'fr': 'Vous ne pouvez pas annuler cette action.',
      'it': 'Non puoi annullare questa azione.',
      'ja': 'この操作を元に戻すことはできません。',
      'pt': 'Você não pode desfazer esta ação.',
    },
    '3ohg2frn': {
      'es': 'Eliminar',
      'ar': 'اِسْتَبْعَد',
      'de': 'Beseitigen',
      'en': 'Eliminate',
      'fr': 'Éliminer',
      'it': 'Eliminare',
      'ja': 'なくす',
      'pt': 'Eliminar',
    },
  },
  // EditProfileComponent
  {
    '0ndwxwme': {
      'es': 'Cambiar foto',
      'ar': 'تغيير الصورة',
      'de': 'Foto ändern',
      'en': 'Change photo',
      'fr': 'Changer de photo',
      'it': 'Cambia foto',
      'ja': '写真を変更する',
      'pt': 'Alterar foto',
    },
    'gmwdgai4': {
      'es': 'Nombre completo',
      'ar': 'الاسم الكامل',
      'de': 'Vollständiger Name',
      'en': 'Full name',
      'fr': 'Nom et prénom',
      'it': 'Nome e cognome',
      'ja': 'フルネーム',
      'pt': 'Nome completo',
    },
    'ycj9vf6t': {
      'es': 'Tu nombre completo...',
      'ar': 'اسمك الكامل...',
      'de': 'Dein vollständiger Name...',
      'en': 'Your full name...',
      'fr': 'Votre nom complet...',
      'it': 'Il tuo nome completo...',
      'ja': 'あなたのフルネームは...',
      'pt': 'Seu nome completo...',
    },
    'l40g2o2w': {
      'es': 'Nombre del negocio',
      'ar': 'اسم العمل',
      'de': 'Firmenname',
      'en': 'Business name',
      'fr': 'Nom de l\'entreprise',
      'it': 'Nome dell\'azienda',
      'ja': '商号',
      'pt': 'Nome comercial',
    },
    'rst8ns6v': {
      'es': 'El Nombre del negocio...',
      'ar': 'اسم العمل...',
      'de': 'Der Name des Unternehmens...',
      'en': 'The name of the business...',
      'fr': 'Le nom de l\'entreprise...',
      'it': 'Il nome dell\'attività...',
      'ja': '事業所の名前は…',
      'pt': 'O nome do negócio...',
    },
    'p2wnkf1z': {
      'es': 'Your Name Business',
      'ar': 'اسمك التجاري',
      'de': 'Ihr Namensunternehmen',
      'en': 'Your Name Business',
      'fr': 'Votre nom d\'entreprise',
      'it': 'Il tuo nome aziendale',
      'ja': 'あなたの名前のビジネス',
      'pt': 'Seu nome comercial',
    },
    'rp1hes4q': {
      'es': 'Numero de teléfono',
      'ar': 'رقم التليفون',
      'de': 'Telefonnummer',
      'en': 'Phone number',
      'fr': 'Numéro de téléphone',
      'it': 'Numero di telefono',
      'ja': '電話番号',
      'pt': 'Número de telefone',
    },
    't2z0bq3o': {
      'es': 'Tu Numero de teléfono...',
      'ar': 'رقم هاتفك...',
      'de': 'Ihre Telefonnummer...',
      'en': 'Your phone number...',
      'fr': 'Votre numéro de téléphone...',
      'it': 'Il tuo numero di telefono...',
      'ja': 'あなたの電話番号...',
      'pt': 'Seu número de telefone...',
    },
    'cqs14uxb': {
      'es': 'Propietario/Fundador',
      'ar': 'المالك/المؤسس',
      'de': 'Inhaber/Gründer',
      'en': 'Owner/Founder',
      'fr': 'Propriétaire/Fondateur',
      'it': 'Proprietario/Fondatore',
      'ja': 'オーナー/創設者',
      'pt': 'Proprietário/Fundador',
    },
    'wsvfjfy7': {
      'es': 'Director',
      'ar': 'مخرج',
      'de': 'Direktor',
      'en': 'Director',
      'fr': 'Directeur',
      'it': 'Direttore',
      'ja': '監督',
      'pt': 'Diretor',
    },
    '6w3e2355': {
      'es': 'Gerente',
      'ar': 'مدير',
      'de': 'Manager',
      'en': 'Manager',
      'fr': 'Directeur',
      'it': 'Manager',
      'ja': 'マネージャー',
      'pt': 'Gerente',
    },
    'm7jyx3gt': {
      'es': 'Gerente medio',
      'ar': 'مدير وسط',
      'de': 'Mittlerer Manager',
      'en': 'Middle Manager',
      'fr': 'Cadre intermédiaire',
      'it': 'Direttore intermedio',
      'ja': '中間管理職',
      'pt': 'Gerente intermediário',
    },
    'xhyu9acv': {
      'es': 'Empleado',
      'ar': 'موظف',
      'de': 'Mitarbeiter',
      'en': 'Employee',
      'fr': 'Employé',
      'it': 'Dipendente',
      'ja': '従業員',
      'pt': 'Funcionário',
    },
    'c6vqzmua': {
      'es': 'Tu Rol',
      'ar': 'دورك',
      'de': 'Ihre Rolle',
      'en': 'Your Role',
      'fr': 'Votre rôle',
      'it': 'Il tuo ruolo',
      'ja': 'あなたの役割',
      'pt': 'Seu papel',
    },
    '0sbx7lp2': {
      'es': 'Busca tu rol...',
      'ar': 'ابحث عن دورك...',
      'de': 'Finden Sie Ihre Rolle...',
      'en': 'Find your role...',
      'fr': 'Trouvez votre rôle...',
      'it': 'Trova il tuo ruolo...',
      'ja': '自分の役割を見つけてください...',
      'pt': 'Encontre o seu papel...',
    },
    'ulncaqo3': {
      'es': 'Descripción corta',
      'ar': 'وصف قصير',
      'de': 'Kurze Beschreibung',
      'en': 'Short description',
      'fr': 'Brève description',
      'it': 'Breve descrizione',
      'ja': '簡単な説明',
      'pt': 'Breve descrição',
    },
    'pwmv9u1p': {
      'es': 'Un poco sobre ti...',
      'ar': 'القليل عنك...',
      'de': 'Ein wenig über dich...',
      'en': 'A little about you...',
      'fr': 'Un peu de toi...',
      'it': 'Un po\' di te...',
      'ja': 'あなたのことを少し...',
      'pt': 'Um pouco sobre você...',
    },
    'kld83ii5': {
      'es': '[bio]',
      'ar': '[السيرة الذاتية]',
      'de': '[Bio]',
      'en': '[bio]',
      'fr': '[biographie]',
      'it': '[biografia]',
      'ja': '[バイオ]',
      'pt': '[biografia]',
    },
    'bn3qps0i': {
      'es': 'Ubicación',
      'ar': 'موقع',
      'de': 'Standort',
      'en': 'Location',
      'fr': 'Emplacement',
      'it': 'Posizione',
      'ja': '位置',
      'pt': 'Localização',
    },
  },
  // subirContenido
  {
    'pin8lecj': {
      'es': 'Subir contenido',
      'ar': 'تحميل المحتوى',
      'de': 'Inhalte hochladen',
      'en': 'Upload content',
      'fr': 'Télécharger du contenu',
      'it': 'Carica contenuto',
      'ja': 'コンテンツをアップロードする',
      'pt': 'Carregar conteúdo',
    },
    '3izk1s5a': {
      'es': 'Presiona para subir',
      'ar': 'اضغط للتحميل',
      'de': 'Zum Hochladen drücken',
      'en': 'Press to upload',
      'fr': 'Appuyez pour télécharger',
      'it': 'Premi per caricare',
      'ja': '押してアップロードします',
      'pt': 'Pressione para carregar',
    },
    '3pfh5fka': {
      'es': 'una imagen o video',
      'ar': 'صورة أو فيديو',
      'de': 'ein Bild oder Video',
      'en': 'an image or video',
      'fr': 'une image ou une vidéo',
      'it': 'un\'immagine o un video',
      'ja': '画像またはビデオ',
      'pt': 'uma imagem ou vídeo',
    },
    '610138gk': {
      'es': 'Agregar',
      'ar': 'يضيف',
      'de': 'Hinzufügen',
      'en': 'Add',
      'fr': 'Ajouter',
      'it': 'Aggiungere',
      'ja': '追加',
      'pt': 'Adicionar',
    },
  },
  // VideoFoto
  {
    'z40itf4v': {
      'es': 'Subir imagen',
      'ar': 'تحميل الصورة',
      'de': 'Bild hochladen',
      'en': 'Upload image',
      'fr': 'Télécharger une image',
      'it': 'Carica immagine',
      'ja': '画像をアップロードする',
      'pt': 'Carregar imagem',
    },
    '32wp8d3a': {
      'es': 'Subir video',
      'ar': 'تحميل الفيديو',
      'de': 'Video hochladen',
      'en': 'Upload video',
      'fr': 'Télécharger la vidéo',
      'it': 'Carica video',
      'ja': 'ビデオをアップロードする',
      'pt': 'Enviar vídeo',
    },
    '4dat8tij': {
      'es': 'Cancelar',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Cancellare',
      'ja': 'キャンセル',
      'pt': 'Cancelar',
    },
  },
  // subirContenidoExclisivo
  {
    'bcn25ebg': {
      'es': 'Subir Contenido Exclusivo',
      'ar': 'تحميل المحتوى الحصري',
      'de': 'Laden Sie exklusive Inhalte hoch',
      'en': 'Upload Exclusive Content',
      'fr': 'Télécharger du contenu exclusif',
      'it': 'Carica contenuti esclusivi',
      'ja': '限定コンテンツをアップロードする',
      'pt': 'Carregar conteúdo exclusivo',
    },
    'ho5ypmn0': {
      'es': 'Foto del evento',
      'ar': 'صورة للحدث',
      'de': 'Foto der Veranstaltung',
      'en': 'Photo of the event',
      'fr': 'Photo de l\'événement',
      'it': 'Foto dell\'evento',
      'ja': 'イベントの写真',
      'pt': 'Foto do evento',
    },
    'm10x1wkn': {
      'es': 'Nombre del evento',
      'ar': 'اسم الحدث',
      'de': 'Veranstaltungsname',
      'en': 'Event name',
      'fr': 'Nom de l\'événement',
      'it': 'Nome dell\'evento',
      'ja': 'イベント名',
      'pt': 'Nome do evento',
    },
    'hjdv31ps': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    '760s6t5q': {
      'es': 'Nombre del evento...',
      'ar': 'اسم الحدث...',
      'de': 'Veranstaltungsname...',
      'en': 'Event name...',
      'fr': 'Nom de l\'événement...',
      'it': 'Nome dell\'evento...',
      'ja': 'イベント名…',
      'pt': 'Nome do evento...',
    },
    'oel37e73': {
      'es': 'Descripción del Evento',
      'ar': 'وصف الحدث',
      'de': 'Ereignisbeschreibung',
      'en': 'Event Description',
      'fr': 'Description de l\'événement',
      'it': 'Descrizione dell\'evento',
      'ja': 'イベントの説明',
      'pt': 'Descrição do Evento',
    },
    'd1ybglfu': {
      'es': '',
      'ar': '',
      'de': '',
      'en': 'A little about you...',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'vlmywgx4': {
      'es': 'Descripción del evento...',
      'ar': 'وصف الحدث...',
      'de': 'Veranstaltungsbeschreibung...',
      'en': 'Event Description...',
      'fr': 'Description de l\'événement...',
      'it': 'Descrizione dell\'evento...',
      'ja': 'イベントの説明...',
      'pt': 'Descrição do evento...',
    },
    '4w9avms5': {
      'es': 'Número de teléfono de contacto',
      'ar': 'رقم هاتف الاتصال',
      'de': 'Kontakttelefonnummer',
      'en': 'Contact phone number',
      'fr': 'Numéro de téléphone du contact',
      'it': 'Contattare il numero di telefono',
      'ja': '連絡先電話番号',
      'pt': 'Telefone de contato',
    },
    'ry28ctiv': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'z9oumd6z': {
      'es': 'Número de teléfono de contacto...',
      'ar': 'رقم الهاتف للتواصل...',
      'de': 'Kontakttelefonnummer...',
      'en': 'Contact phone number...',
      'fr': 'Numéro de téléphone du contact...',
      'it': 'Contattare il numero di telefono...',
      'ja': '連絡先電話番号...',
      'pt': 'Telefone para contato...',
    },
    '57ux7h66': {
      'es': '',
      'ar': '',
      'de': '',
      'en': 'Your Network...',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'amfllyho': {
      'es': 'Propietario/Fundador',
      'ar': 'المالك/المؤسس',
      'de': 'Inhaber/Gründer',
      'en': 'Owner/Founder',
      'fr': 'Propriétaire/Fondateur',
      'it': 'Proprietario/Fondatore',
      'ja': 'オーナー/創設者',
      'pt': 'Proprietário/Fundador',
    },
    'emediuo5': {
      'es': 'Director',
      'ar': 'مخرج',
      'de': 'Direktor',
      'en': 'Director',
      'fr': 'Directeur',
      'it': 'Direttore',
      'ja': '監督',
      'pt': 'Diretor',
    },
    '9l4rnfp8': {
      'es': 'Gerente',
      'ar': 'مدير',
      'de': 'Manager',
      'en': 'Manager',
      'fr': 'Directeur',
      'it': 'Manager',
      'ja': 'マネージャー',
      'pt': 'Gerente',
    },
    't0tnqlqm': {
      'es': 'Gerente medio',
      'ar': 'مدير وسط',
      'de': 'Mittlerer Manager',
      'en': 'Middle Manager',
      'fr': 'Cadre intermédiaire',
      'it': 'Direttore intermedio',
      'ja': '中間管理職',
      'pt': 'Gerente intermediário',
    },
    'bwc6po0b': {
      'es': 'Empleado',
      'ar': 'موظف',
      'de': 'Mitarbeiter',
      'en': 'Employee',
      'fr': 'Employé',
      'it': 'Dipendente',
      'ja': '従業員',
      'pt': 'Funcionário',
    },
    'f2844zwo': {
      'es': 'Tu Network...',
      'ar': 'شبكتك...',
      'de': 'Ihr Netzwerk...',
      'en': 'Your Network...',
      'fr': 'Votre réseau...',
      'it': 'La tua rete...',
      'ja': 'あなたのネットワーク...',
      'pt': 'Sua rede...',
    },
    'omxlymnz': {
      'es': 'Search for an item...',
      'ar': 'البحث عن عنصر...',
      'de': 'Nach einem Artikel suchen...',
      'en': 'Search for an item...',
      'fr': 'Rechercher un article...',
      'it': 'Cerca un articolo...',
      'ja': 'アイテムを検索...',
      'pt': 'Procure um item...',
    },
    '78qkmlek': {
      'es': 'Location',
      'ar': 'موقع',
      'de': 'Standort',
      'en': 'Location',
      'fr': 'Emplacement',
      'it': 'Posizione',
      'ja': '位置',
      'pt': 'Localização',
    },
  },
  // comentarios
  {
    'yewl94x9': {
      'es': 'Comentarios',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    '4pw8z845': {
      'es': 'Responder',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    '1l2q197y': {
      'es': 'Añadir comentario...',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
  },
  // respuestaComentarios
  {
    'u2yb4y9v': {
      'es': 'Añadir comentario...',
      'ar': 'إضافة تعليق...',
      'de': 'Kommentar hinzufügen...',
      'en': 'Add comment...',
      'fr': 'Ajouter un commentaire...',
      'it': 'Aggiungi commento...',
      'ja': 'コメントを追加...',
      'pt': 'Adicionar comentário...',
    },
  },
  // MapaMessageBottom
  {
    'yv0zaplc': {
      'es': 'Dirección',
      'ar': 'عنوان',
      'de': 'Adresse',
      'en': 'Address',
      'fr': 'Adresse',
      'it': 'Indirizzo',
      'ja': '住所',
      'pt': 'Endereço',
    },
  },
  // onBoardComplete_modal
  {
    '6t67tq7o': {
      'es': 'Felicitaciones!',
      'ar': 'تهانينا!',
      'de': 'Glückwunsch!',
      'en': 'Congratulations!',
      'fr': 'Félicitations!',
      'it': 'Congratulazioni!',
      'ja': 'おめでとう！',
      'pt': 'Parabéns!',
    },
    '6wussefj': {
      'es':
          'Su cuenta está lista para usar. Será redirigido a la página de inicio en unos segundos.',
      'ar':
          'حسابك جاهز للاستخدام. سيتم إعادة توجيهك إلى الصفحة الرئيسية في بضع ثوان.',
      'de':
          'Ihr Konto ist einsatzbereit. Sie werden in wenigen Sekunden zur Startseite weitergeleitet.',
      'en':
          'Your account is ready to use. You will be redirected to the home page in a few seconds.',
      'fr':
          'Votre compte est prêt à être utilisé. Vous serez redirigé vers la page d\'accueil dans quelques secondes.',
      'it':
          'Il tuo account è pronto per l\'uso. Verrai reindirizzato alla home page in pochi secondi.',
      'ja': 'アカウントを使用する準備ができました。数秒以内にホームページにリダイレクトされます。',
      'pt':
          'Sua conta está pronta para uso. Você será redirecionado para a página inicial em alguns segundos.',
    },
  },
  // InfoConfirm_Modal
  {
    'vdpw6bkh': {
      'es': 'Cancelar',
      'ar': 'يلغي',
      'de': 'Stornieren',
      'en': 'Cancel',
      'fr': 'Annuler',
      'it': 'Cancellare',
      'ja': 'キャンセル',
      'pt': 'Cancelar',
    },
    '3nstf8lu': {
      'es': 'Ok, entiendo',
      'ar': 'حسنا أنا أفهم',
      'de': 'Okay, ich verstehe',
      'en': 'Okay I understand',
      'fr': 'ok je comprends',
      'it': 'Ok, capisco',
      'ja': 'わかりました、わかりました',
      'pt': 'Ok, eu entendo',
    },
  },
  // Miscellaneous
  {
    '80og77uo': {
      'es':
          'Para tomar una foto o video, esta aplicación requiere permiso para acceder a la camara',
      'ar':
          'لالتقاط صورة أو مقطع فيديو، يتطلب هذا التطبيق إذنًا للوصول إلى الكاميرا',
      'de':
          'Um ein Foto oder Video aufzunehmen, benötigt diese Anwendung die Erlaubnis, auf die Kamera zuzugreifen',
      'en':
          'To take a photo or video, this app requires permission to access the camera.',
      'fr':
          'Pour prendre une photo ou une vidéo, cette application nécessite une autorisation pour accéder à la caméra',
      'it':
          'Per scattare una foto o registrare un video, questa applicazione richiede l\'autorizzazione per accedere alla fotocamera',
      'ja': '写真やビデオを撮影するには、このアプリケーションはカメラへのアクセス許可を必要とします',
      'pt':
          'Para tirar uma foto ou gravar um vídeo, este aplicativo requer permissão para acessar a câmera',
    },
    'xnlrz6n4': {
      'es':
          'Para grabar audio para un video, esta aplicación requiere permiso para acceder al microfono',
      'ar':
          'لتسجيل الصوت لمقطع فيديو، يتطلب هذا التطبيق إذنًا للوصول إلى الميكروفون',
      'de':
          'Um Audio für ein Video aufzunehmen, benötigt diese App die Erlaubnis, auf das Mikrofon zuzugreifen',
      'en':
          'To record audio for a video, this app requires permission to access the microphone.',
      'fr':
          'Pour enregistrer l\'audio d\'une vidéo, cette application nécessite l\'autorisation d\'accéder au microphone',
      'it':
          'Per registrare l\'audio per un video, questa applicazione richiede l\'autorizzazione per accedere al microfono',
      'ja': 'ビデオの音声を録音するには、このアプリケーションにはマイクへのアクセス許可が必要です',
      'pt':
          'Para gravar áudio de um vídeo, este aplicativo requer permissão para acessar o microfone',
    },
    '06qxlh0j': {
      'es':
          'Para cargar datos, esta aplicación requiere permiso para acceder a labiblioteca de fotos',
      'ar': 'لتحميل البيانات، يتطلب هذا التطبيق إذنًا للوصول إلى مكتبة الصور',
      'de':
          'Um Daten hochzuladen, benötigt diese App die Erlaubnis, auf die Fotobibliothek zuzugreifen',
      'en':
          'To load data, this app requires permission to access the photo library.',
      'fr':
          'Pour télécharger des données, cette application nécessite l\'autorisation d\'accéder à la photothèque',
      'it':
          'Per caricare i dati, questa app richiede l\'autorizzazione per accedere alla libreria di foto',
      'ja': 'データをアップロードするには、このアプリには写真ライブラリへのアクセス許可が必要です',
      'pt':
          'Para fazer upload de dados, este aplicativo requer permissão para acessar a biblioteca de fotos',
    },
    'xa5a1oz3': {
      'es':
          'Para buscar cerca, esta aplicación requiere acceso a su ubicación actual.',
      'ar': 'للبحث في مكان قريب، يتطلب هذا التطبيق الوصول إلى موقعك الحالي.',
      'de':
          'Um in der Nähe zu suchen, benötigt diese App Zugriff auf Ihren aktuellen Standort.',
      'en':
          'To search nearby, this app requires access to your current location.',
      'fr':
          'Pour effectuer une recherche à proximité, cette application nécessite l\'accès à votre position actuelle.',
      'it':
          'Per effettuare ricerche nelle vicinanze, questa app richiede l\'accesso alla tua posizione attuale.',
      'ja': '近くを検索するには、このアプリは現在地にアクセスする必要があります。',
      'pt':
          'Para pesquisar nas proximidades, este aplicativo requer acesso à sua localização atual.',
    },
    'zlvwooqc': {
      'es':
          'Esta aplicación requiere permisos para realizar una verificación biométrica',
      'ar': 'يتطلب هذا التطبيق أذونات لإجراء التحقق البيومتري',
      'de':
          'Diese App erfordert Berechtigungen zur Durchführung der biometrischen Überprüfung',
      'en': 'This app requires permissions to perform biometric verification',
      'fr':
          'Cette application nécessite des autorisations pour effectuer une vérification biométrique',
      'it':
          'Questa app richiede le autorizzazioni per eseguire la verifica biometrica',
      'ja': 'このアプリには生体認証を実行するための権限が必要です',
      'pt':
          'Este aplicativo requer permissões para realizar verificação biométrica',
    },
    'r3y8g4od': {
      'es': 'Error',
      'ar': 'خطأ',
      'de': 'Fehler',
      'en': 'Mistake',
      'fr': 'Erreur',
      'it': 'Errore',
      'ja': '間違い',
      'pt': 'Erro',
    },
    'resnrgm3': {
      'es': 'Restablecer contraseña, mensaje enviado',
      'ar': 'إعادة تعيين كلمة المرور، تم إرسال الرسالة',
      'de': 'Passwort zurücksetzen, Nachricht gesendet',
      'en': 'Reset password, message sent',
      'fr': 'Réinitialiser le mot de passe, message envoyé',
      'it': 'Reimposta password, messaggio inviato',
      'ja': 'パスワードをリセットし、メッセージを送信しました',
      'pt': 'Redefinir senha, mensagem enviada',
    },
    'oagewzi6': {
      'es': 'Correo requerido',
      'ar': 'البريد الإلكتروني مطلوب',
      'de': 'E-Mail erforderlich',
      'en': 'Email required',
      'fr': 'E-mail requis',
      'it': 'E-mail richiesta',
      'ja': 'メールアドレスが必要です',
      'pt': 'E-mail obrigatório',
    },
    'e6opgmjr': {
      'es': 'Se requiere un número de teléfono y tiene que empesar con +',
      'ar': 'رقم الهاتف مطلوب ويجب أن يبدأ بـ +',
      'de': 'Eine Telefonnummer ist erforderlich und muss mit + beginnen',
      'en': 'A phone number is required and must start with +',
      'fr': 'Un numéro de téléphone est obligatoire et doit commencer par +',
      'it': 'È obbligatorio un numero di telefono che deve iniziare con +',
      'ja': '電話番号は必須であり、+ で始まる必要があります',
      'pt': 'Um número de telefone é obrigatório e deve começar com +',
    },
    'pmjqyz1z': {
      'es': 'Contraseñas no coinciden',
      'ar': 'كلمات المرور غير متطابقة',
      'de': 'Passwörter stimmen nicht überein',
      'en': 'Passwords do not match',
      'fr': 'Les mots de passe ne correspondent pas',
      'it': 'Le password non corrispondono',
      'ja': 'パスワードが一致しません',
      'pt': 'As senhas não coincidem',
    },
    '61ar9idi': {
      'es': 'Introduzca el código de verificación por SMS',
      'ar': 'أدخل رمز التحقق عبر الرسائل القصيرة',
      'de': 'Geben Sie den SMS-Bestätigungscode ein',
      'en': 'Enter the SMS verification code',
      'fr': 'Entrez le code de vérification par SMS',
      'it': 'Inserisci il codice di verifica via SMS',
      'ja': 'SMS認証コードを入力してください',
      'pt': 'Insira o código de verificação por SMS',
    },
    '8id3z5cm': {
      'es':
          'Demasiado tiempo desde el inicio de sesión más reciente. Inicie sesión nuevamente',
      'ar':
          'لقد مر وقت طويل جدًا منذ آخر تسجيل دخول. قم بتسجيل الدخول مرة أخرى',
      'de': 'Die letzte Anmeldung ist zu lange her. Melden Sie sich erneut an',
      'en': 'Too much time since last login. Please log in again',
      'fr':
          'Trop longtemps depuis la dernière connexion. Connectez-vous à nouveau',
      'it': 'Troppo tempo dall\'ultimo accesso. Accedi di nuovo',
      'ja': '最後にログインしてから時間が経過しすぎています。再度サインインしてください',
      'pt': 'Muito tempo desde o login mais recente. Faça login novamente',
    },
    '8e1yykvf': {
      'es':
          'Demasiado tiempo desde el inicio de sesión más reciente. Inicie sesión nuevamente antes de actualizar',
      'ar':
          'لقد مضى وقت طويل جدًا منذ آخر تسجيل دخول. الرجاء تسجيل الدخول مرة أخرى قبل التحديث',
      'de':
          'Die letzte Anmeldung ist zu lange her. Bitte melden Sie sich vor der Aktualisierung erneut an',
      'en':
          'Too much time since last login. Please log in again before updating.',
      'fr':
          'Trop longtemps depuis la dernière connexion. Veuillez vous reconnecter avant de mettre à jour',
      'it':
          'Troppo tempo dall\'ultimo accesso. Accedi nuovamente prima dell\'aggiornamento',
      'ja': '最後にログインしてから時間が経過しすぎています。更新する前にもう一度サインインしてください',
      'pt':
          'Muito tempo desde o login mais recente. Faça login novamente antes de atualizar',
    },
    'x0mtssee': {
      'es': 'Correo de confirmación de cambio de email enviado!',
      'ar': 'تم إرسال بريد إلكتروني لتأكيد تغيير البريد الإلكتروني!',
      'de': 'Bestätigungs-E-Mail zur E-Mail-Änderung gesendet!',
      'en': 'Email change confirmation email sent!',
      'fr': 'E-mail de confirmation de modification envoyé !',
      'it': 'Email di conferma modifica email inviata!',
      'ja': 'メールアドレス変更確認メールを送信しました!',
      'pt': 'E-mail de confirmação de alteração de e-mail enviado!',
    },
    'y8knomhv': {
      'es': 'El correo electrónico ya está en uso por otra cuenta',
      'ar': 'البريد الإلكتروني قيد الاستخدام بالفعل من قبل حساب آخر',
      'de': 'E-Mail wird bereits von einem anderen Konto verwendet',
      'en': 'The email is already in use by another account',
      'fr': 'L\'e-mail est déjà utilisé par un autre compte',
      'it': 'L\'e-mail è già utilizzata da un altro account',
      'ja': '電子メールはすでに別のアカウントで使用されています',
      'pt': 'O e-mail já está em uso por outra conta',
    },
    '63pofxx8': {
      'es':
          'La credencial de autenticación  suministrada es incorrecta, está mal formada o ha caducado',
      'ar':
          'بيانات اعتماد المصادقة المقدمة غير صحيحة أو مشوهة أو منتهية الصلاحية',
      'de':
          'Die angegebenen Authentifizierungsdaten sind falsch, fehlerhaft oder abgelaufen',
      'en':
          'The authentication credential supplied is incorrect, malformed, or has expired',
      'fr':
          'Les informations d\'authentification fournies sont incorrectes, mal formées ou expirées',
      'it':
          'La credenziale di autenticazione fornita non è corretta, non è valida o è scaduta',
      'ja': '提供された認証資格情報が間違っているか、不正な形式であるか、期限切れです。',
      'pt':
          'A credencial de autenticação fornecida está incorreta, malformada ou expirou',
    },
    'eshv3d0u': {
      'es': 'Formato de archivo no valido',
      'ar': 'تنسيق الملف غير صالح',
      'de': 'Ungültiges Dateiformat',
      'en': 'Invalid file format',
      'fr': 'Format de fichier invalide',
      'it': 'Formato file non valido',
      'ja': '無効なファイル形式です',
      'pt': 'Formato de arquivo inválido',
    },
    'nra9vgw0': {
      'es': 'Cargando el archivo...',
      'ar': 'جارٍ تحميل الملف...',
      'de': 'Datei wird geladen...',
      'en': 'Loading file...',
      'fr': 'Chargement du fichier...',
      'it': 'Caricamento del file...',
      'ja': 'ファイルをロード中...',
      'pt': 'Carregando o arquivo...',
    },
    'pnd5gw85': {
      'es': 'Exito',
      'ar': 'نجاح',
      'de': 'Erfolg',
      'en': 'Success',
      'fr': 'Succès',
      'it': 'Successo',
      'ja': '成功',
      'pt': 'Sucesso',
    },
    '6dv9i6ph': {
      'es': 'Error al cargar datos',
      'ar': 'حدث خطأ أثناء تحميل البيانات',
      'de': 'Fehler beim Laden der Daten',
      'en': 'Error loading data',
      'fr': 'Erreur de chargement des données',
      'it': 'Errore durante il caricamento dei dati',
      'ja': 'データのロード中にエラーが発生しました',
      'pt': 'Erro ao carregar dados',
    },
    'krkdu1oh': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'idk4ni52': {
      'es': 'Elija la fuente (galería o cámara)',
      'ar': 'اختر المصدر (المعرض أو الكاميرا)',
      'de': 'Wählen Sie die Quelle (Galerie oder Kamera)',
      'en': 'Choose the source (gallery or camera)',
      'fr': 'Choisissez la source (galerie ou caméra)',
      'it': 'Scegli la fonte (galleria o fotocamera)',
      'ja': 'ソースを選択します (ギャラリーまたはカメラ)',
      'pt': 'Escolha a fonte (galeria ou câmera)',
    },
    'yp837btj': {
      'es': 'Galería',
      'ar': 'معرض',
      'de': 'Galerie',
      'en': 'Gallery',
      'fr': 'Galerie',
      'it': 'Galleria',
      'ja': 'ギャラリー',
      'pt': 'Galeria',
    },
    'k9l5nxjt': {
      'es': 'Galería (fotos)',
      'ar': 'معرض (صور)',
      'de': 'Galerie (Fotos)',
      'en': 'Gallery (photos)',
      'fr': 'Galerie (photos)',
      'it': 'Galleria (foto)',
      'ja': 'ギャラリー（写真）',
      'pt': 'Galeria (fotos)',
    },
    'p5lytjj1': {
      'es': 'Galería (video)',
      'ar': 'معرض (فيديو)',
      'de': 'Galerie (Video)',
      'en': 'Gallery (video)',
      'fr': 'Galerie (vidéo)',
      'it': 'Galleria (video)',
      'ja': 'ギャラリー（ビデオ）',
      'pt': 'Galeria (vídeo)',
    },
    '0b6gsrbc': {
      'es': 'Camara',
      'ar': 'آلة تصوير',
      'de': 'Kamera',
      'en': 'Camera',
      'fr': 'Caméra',
      'it': 'Telecamera',
      'ja': 'カメラ',
      'pt': 'Câmera',
    },
    '62kla7gb': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    '8dq61zfj': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'l1f80it2': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
    'r9m8e63c': {
      'es': '',
      'ar': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
    },
  },
].reduce((a, b) => a..addAll(b));
